version: '3.8'

services:
  restaurants_postgres:
    image: postgres:13
    container_name: BankOneCoindb
    environment:
      POSTGRES_USER: ONECOIN
      POSTGRES_PASSWORD: SystemBank0101@
      POSTGRES_DB: bankOneCoin_db
    ports:
      - "5435:5432"
    volumes:
      - BankOneCoindb_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  BankOneCoindb_postgres_data: